const fs = require('fs');
global.KILN_DATA = require('../data/kiln.json');
const src = fs.readFileSync(require('path').join(__dirname, '..', 'app.js'), 'utf8');
const module2 = { exports: {} };
new Function('module', 'window', src)(module2, undefined);
const m = module2.exports.buildModel(global.KILN_DATA);
console.log('TC:', JSON.stringify(m.tcReport));
const ramps = m.cars.map(c => c.ramp).sort((a, b) => a - b);
console.log('ramp min/5%/50%/95%/max:', ramps[0].toFixed(2), ramps[6].toFixed(2), ramps[60].toFixed(2), ramps[113].toFixed(2), ramps[119].toFixed(2));
const rb = m.cars.filter(c => c.rampBad);
console.log('rampBad:', rb.length, rb.map(c => c.id + ':' + c.ramp.toFixed(2)).join(' '));
const tb = m.cars.filter(c => c.tempBad);
console.log('tempBad:', tb.length, tb.map(c => c.id + ':' + c.peakFire.toFixed(0) + (c.tempBad.over ? 'over' : 'under')).join(' '));
console.log('jams:', JSON.stringify(m.jams));
console.log('flameouts:', m.flameouts.map(f => f.burner + ' ' + f.from + '-' + f.to).join(' | '));
console.log('ratioBad:', m.ratioBad.map(f => f.burner + ' ' + f.from + '-' + f.to + ' min' + f.min.toFixed(1) + ' max' + f.max.toFixed(1)).join(' | '));
console.log('maxFlow:', m.maxFlowEvents.map(e => e.from + '-' + e.to + ' ' + Object.keys(e.kilns).join('/') + ' ' + Object.entries(e.verdict).map(([k, v]) => k + (v.high ? '高负荷' : '开度没退') + '(' + v.factor.toFixed(2) + ')').join(',')).join('\n'));
console.log('gas:', m.totalGas.toFixed(0), 'tons:', m.totalTons.toFixed(1), 'unit:', m.unit.toFixed(1));
console.log('A:', m.scenA.gas.toFixed(0), m.scenA.count, m.scenA.unit.toFixed(1), ' B:', m.scenB.gas.toFixed(0), m.scenB.count, m.scenB.unit.toFixed(1));
console.log('onlyA:', m.onlyA.join(','));
console.log('onlyB:', m.onlyB.join(','));
